swagger: "2.0"
info:
  description: |
    This is a Twitter API interface.

  version: "1.0.0"
  title: Tilting At Windmills
  contact:
    name: allan.cochrane@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: petstore.swagger.wordnik.com
basePath: /v2
schemes:
  - http
paths:
  /tweets/:screen_name:
    get:
      summary: Finds Tweets by a user
      description: Returns an array of the text of recent tweets
      produces:
        - application/json
      parameters:
        - in: query
          name: screen_name
          description: Screen name for user for tweets
          required: true
          type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              type: string
        "400":
          description: Errors
          schema:
            type: object
  /common/:screen_name1/:screen_name2:
    get:
      summary: Finds shared followers
      description: Returns an array of shared follower names.
      produces:
        - application/json
      parameters:
        - in: query
          name: screen_name1
          description: First name to find
          required: true
          type: string
        - in: query
          name: screen_name2
          description: Second name to find
          required: true
          type: string
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              type: string
        "400":
          description: Errors
          schema:
            type: object
        "404":
          description: Errors
          schema:
            type: object
